application: planet-linux-of-taiwan
version: 1
runtime: python
api_version: 1

handlers:
- url: /s
  static_dir: static
- url: /join
  script: join.py
- url: /admin
  script: admin.py
  login: admin
- url: /admin/.*
  script: admin.py
  login: admin
- url: /.*
  script: index.py
